
		<div class="panel panel-default">
	        <div class="head">
                  <h1>Edit News Item
                  		<span class="but">
                  			<?php echo anchor("news", "<i class=\"fa icon-list fa-fw\"></i> View All", 'class="btn btn-info"') ?>
                  		</span>
                  </h1>
            </div> 
		   
			<div class="inner" id="cms_content_area">

                <?php if( !empty($message) ){ ?>
	                <div class="alert alert-error">  
					  <a class="close" data-dismiss="alert">x</a>  
					  <?php echo $message ?>  
					</div> 
				<?php } ?>

				<form id="cms_form" method="post" enctype="multipart/form-data" action="<?php echo site_url("news/edit/$id") ?>">
	                <fieldset>
						<div class="leftfloat">
							
				<div class="input select required">
				    <label for="title">News Title:</label>
				    <input class="form-control " name="title" size="30" type="text" id="title" placeholder="News Title" value="<?php echo set_value("title", $details->title) ?>">
			    </div>
			
				<div class="input select required">
				    <label for="summary">Summary:</label>
				    <textarea class="form-control " rows="5" cols="20" name="summary" id="summary" placeholder="News Summary"><?php echo set_value("summary", $details->summary) ?></textarea>
			    </div>
			
				<div class="input select required">
				    <label for="content">Content:</label>
				    <textarea class="form-control " rows="5" cols="20" name="content" id="content" placeholder="News Content"><?php echo set_value("content", $details->content) ?></textarea>
			    </div>
			
			    <div class="input <?php if (form_error("picture")) echo "form-group has-error"; ?>">								   	 
					<?php if(!empty($details->picture)){ ?>
						<input type="hidden" id="current_picture" name="current_picture" value="<?php echo $details->picture ?>">
				   		<p>
			<img alt="Picture" src="<?php echo base_url( "uploads/news/$details->picture" ) ?>" border="0" height="110" width="110" title="Current Picture"></p>
	            	<?php } ?>
	                <label for="picture">Picture</label>
	                <?php echo form_error("picture"); ?>
				    <input class="form-control " type="file" name="picture" id="picture">
			   </div>
			
				<div class="input select <?php if (form_error("news_category")) echo "form-group has-error"; ?>">
				    <label for="news_category">News Category:</label>
					<?php echo form_dropdown("news_category", $news_category_options, $details->news_category,"class=\"form-control \"") ?> 
			    </div>
			
				<div class="input select required">
				    <label for="news_date">News Date:</label>
				    <input class="form-control datepicker " name="news_date" size="30" type="text" id="news_date" placeholder="News Date" value="<?php echo set_value("news_date", $details->news_date) ?>">
			    </div>
			
				<div class="input select required">
				    <label for="active">Published:</label>
					
				<input style="width:7%" type="radio" name="active" value="0" <?php  echo ($details->active == 0)? "checked=\"checked\"":"" ?> > NO
				<input style="width:7%" type="radio" name="active" value="1" <?php  echo ($details->active == 1)? "checked=\"checked\"":"" ?> > YES	
			    </div>
									   

					   </div>
					    <?php echo form_hidden("news_id", $id); ?>
					    						                 
	                </fieldset>
					<div class="submit">
						<button type="submit" class="btn btn-info btn-lg"><i class="fa icon-save fa-fw"></i> Save</button>

						<?php echo anchor("news", "<i class=\"icon-white icon-remove\"></i> Cancel", 'class="btn btn-default btn-danger btn-xs" style="margin-left:145px;"') ?>					
					</div>
				</form>

	        </div>
		</div>
			

	<!-- File generated by http://www.generatecms.com on 04/11/2014 09:09:44 pm -->
	