
		<div class="panel panel-default">
	        <div class="head">
                 	<h1>News  
                 		<span class="but">
                 			<?php echo anchor("news/edit", "<i class=\"fa icon-plus fa-fw\"></i> Add New", 'class="btn btn-info"') ?>
                 		</span>
                 	</h1>
            </div>

			<div class="inner" id="cms_content_area">					
						<table id="<?php echo $table_id ?>" class="bordered-table zebra-striped">
							<thead>
								<tr>
									
									<th>news_id</th>
									<th>News Title</th>
									<th>Picture</th>
									<th>News Category</th>
									<th>News Date</th>
									<th>Published</th>
									<th>Action</th>								
								</tr>
							</thead>
							<tbody>															
							</tbody>
						</table>						
	        </div>
		</div>
			

	<!-- File generated by http://www.generatecms.com on 04/11/2014 09:09:44 pm -->
	