<div class="panel panel-default">
            <div class="head">
                  <h1>Change Password</h1>
            </div> 
               
            <div class="inner" id="cms_content_area">

                <?php if( !empty($message) ){ ?>
                      <div class="alert alert-error">  
                                <a class="close" data-dismiss="alert">x</a>  
                                <?php echo $message ?>  
                              </div> 
                        <?php } ?>

                  <?php echo form_open("auth/change_password"); ?>
                  <fieldset>
                        <div class="leftfloat">
                              
                              <div class="input select required">
                                  <label for="old_password"><?php echo lang('change_password_old_password_label', 'old_password');?></label>
                                  <?php echo form_input($old_password) ?>
                              </div>
                              
                              <div class="input select required">
                                  <label for="new_password"><?php echo sprintf(lang('change_password_new_password_label'), $min_password_length);?></label>
                                  <?php echo form_input($new_password) ?>
                              </div>

                              <div class="input select required">
                                  <label for="new_password_confirm"><?php echo lang('change_password_new_password_confirm_label', 'new_password_confirm');?></label>
                                  <?php echo form_input($new_password_confirm);?>
                              </div>                                                                                               

                              <?php echo form_input($user_id);?>
                        </div>                        
                  </fieldset>
                  <div class="submit">
                        <button type="submit" class="btn btn-info btn-lg"><i class="fa icon-save fa-fw"></i> <?php echo lang('change_password_submit_btn'); ?></button>
                  </div>
                  <?php echo form_close();?>      
      </div>
</div>
                  
<!-- File generated by http://www.getcms.com on 03/23/2014 05:33:38 pm -->      
