
		<div class="panel panel-default">
	        <div class="head">
                  <h1>Edit News_category Item
                  		<span class="but">
                  			<?php echo anchor("news_category", "<i class=\"fa icon-list fa-fw\"></i> View All", 'class="btn btn-info"') ?>
                  		</span>
                  </h1>
            </div> 
		   
			<div class="inner" id="cms_content_area">

                <?php if( !empty($message) ){ ?>
	                <div class="alert alert-error">  
					  <a class="close" data-dismiss="alert">x</a>  
					  <?php echo $message ?>  
					</div> 
				<?php } ?>

				<form id="cms_form" method="post"  action="<?php echo site_url("news_category/edit/$id") ?>">
	                <fieldset>
						<div class="leftfloat">
							
				<div class="input select required">
				    <label for="category_name">Category Name:</label>
				    <input class="form-control " name="category_name" size="30" type="text" id="category_name" placeholder="The name of the category" value="<?php echo set_value("category_name", $details->category_name) ?>">
			    </div>
									   

					   </div>
					    <?php echo form_hidden("news_category_id", $id); ?>
					    						                 
	                </fieldset>
					<div class="submit">
						<button type="submit" class="btn btn-info btn-lg"><i class="fa icon-save fa-fw"></i> Save</button>
					</div>
				</form>

	        </div>
		</div>
			

	<!-- File generated by http://www.generatecms.com on 04/11/2014 09:09:44 pm -->
	