
		<div class="panel panel-default">
	        <div class="head">
                 	<h1>System Users
                 		<span class="but">
                 			<?php echo anchor("auth/user_edit", "<i class=\"fa icon-plus fa-fw\"></i> Add New", 'class="btn btn-info"') ?>
                 		</span>
                 	</h1>
            </div>

			<div class="inner" id="cms_content_area">					
					<?php if(!empty($items) && is_array($items) ) { ?>	
						<table id="cms_listing_tbl" class="table table-striped table-hover">
							<thead>
								<tr>
									<th>Sn</th>	
									<th>Username</th>
									<th>Email</th>
									<th>Last Login</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>	
							<?php 
								foreach ($items as $user) { 
									if($user->active){
										$uri = "auth/unpublish/";
										$label = "<i class=\"fa icon-ban fa-fw\"></i> Unpublish";
									}
									else {
										$uri = "auth/publish/";
										$label = "<i class=\"fa icon-eye fa-fw\"></i> Publish";	
									}
								?>
								<tr class="even gradeA">
									<td><?php echo $sn ?></td>  
									<td><?php echo $user->username ?></td>
									<td><?php echo $user->email ?></td>
									<td><?php echo $user->last_login ?></td>
									<td>
										<?php echo anchor("auth/user_edit/".$user->id, "<i class=\"fa icon-edit fa-fw\"></i>") ?> 
										<?php //echo anchor("auth/user_delete/".$user->id, "<i class=\"fa icon-trash fa-fw\"></i>", 'class="delete" title="this user"') ?> 
										<?php //echo anchor($uri.$user->id, $label) ?>
									</td>
								</tr>
							<?php 
							$sn++;
							} 
							?>								
							</tbody>
						</table>
						<div class="pagination">
							<ul>
								<?php echo $links ?>
							</ul>
						</div>
					<?php } else { ?> <p>No Users Added.</p> <?php } ?>
	        </div>
		</div>
			

	<!-- File generated by http://www.getcms.com on 03/18/2014 10:29:19 pm -->
	
