	</div> <!-- close row div -->

	<div id="footer" class="row">
		<p>&copy; 2014 CMS.All rights reserved.</p>
		<p>Generated by <a target="_blank" href="http://www.generatecms.com">genCMS</a></p>
	</div>

</div><!-- close container div -->
</body>
</html>
