
		<?php if ($this->ion_auth->logged_in() ){ ?>	
		<ul class="nav nav-pills">
		  <li class="active"><a href="<?php echo site_url() ?>"><i class="fa icon-home fa-fw"></i> Home</a></li>
		  <li><a href="<?php echo site_url("auth/list_users") ?>"><i class="fa icon-group fa-fw"></i> Users</a></li>
		  
				<li><a href="<?php echo site_url("news") ?>"><i class="fa icon-th-large fa-fw"></i> News</a></li>
				<li><a href="<?php echo site_url("news_category") ?>"><i class="fa icon-th-large fa-fw"></i> News Category</a></li>		  
		  <li class="dropdown" style="float:right;">
		    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
				<i class="fa icon-user fa-fw"></i>
		      	<?php echo $this->ion_auth->user()->row()->email ?><span class="caret"></span>
		    </a>
		    <ul class="dropdown-menu">
		    	<li><a href="<?php echo site_url("auth/change_password") ?>"><i class="fa icon-key fa-fw"></i>Change Password</a></li>
		      	<li><a href="<?php echo site_url("auth/logout") ?>"><i class="fa icon-signout fa-fw"></i>Logout</a></li>
		    </ul>
		  </li>
		</ul>
		<?php } ?>
			

	<!-- File generated by http://www.generatecms.com on 04/11/2014 09:09:44 pm -->
	